import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Box from '@mui/material/Box'
import './globals.css'
import { Footer, Header } from './components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Box>
        <Header/>
        <Box sx={{overflowY: "auto"}}>{children}</Box>
        <Footer/>
      </Box>
      </body>
    </html>
  )
}
